#!/bin/bash

# Resolve missing shared libraries and install necessary packages to fix them
# Copyright (C) 2017 Amardhruva Prabhu

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.



USEERROR="$0:wrong number of parameters"

USAGE="
USAGE
$0 executable
"

if [ $# -ne 1 ]
then
	echo "$USEERROR"
	echo "$USAGE"
	exit 1
fi

EXEC_ARCH=`objdump -f $1| awk '/architecture/{gsub(/,$/,"",$2);print $2}'`

if [ `uname -m` = $EXEC_ARCH ]
then
	SUFFIX=""
else
	SUFFIX=":$EXEC_ARCH"
fi


MISSING_SHARED_LIBS=`ldd $1 | grep "found" | cut -d " " -f1`

COUNT=`echo $MISSING_SHARED_LIBS | wc -w`

if [ $COUNT -eq 0 ]
then
	echo "NO missing libraries"
	exit 0
fi

echo "$COUNT missing libs"

for i in $MISSING_SHARED_LIBS
do
	PACKAGE=`apt-file -l search $i`
	echo $PACKAGE$SUFFIX
	MISSING_PKGS="$MISSING_PKGS$PACKAGE$SUFFIX "
done

sudo apt install $MISSING_PKGS
